baseURL = 'https://joseluna.dev/'
languageCode = 'es-mx'
title = 'José Luna' # Cambiado a solo el nombre para que no se repita
theme = "hugo-blog-awesome"
enableEmoji = true

[params]
  sitename = "José Luna | Blog de DevOps y homelab" # Aquí va el título largo
  defaultColor = "dark" # dark, light, auto
  description = "Blog personal de Jose Luna sobre DevOps y homelab"
  mainSections = ['posts']
  toc = false
  goToTop = true
  dateFormat = "2 de enero de 2006" # Formato de fecha en español

[params.author]
  name = "Jose Luna"
  intro = "Bienvenido a mi blog"
  description = "Aqui compartire mis aventuras de docker y mas..."

[params.webmanifest]
  theme_color = "#3498db"
  background_color = "#131418"
  display = "standalone"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[[menu.main]]
  name = 'Inicio'
  url = '/'
  weight = 10

[[menu.main]]
  name = 'Sobre mí'
  url = '/about/'
  weight = 15

# [[menu.main]]
#   name = 'Posts'
#   url = '/posts/'
#   weight = 20

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/chachoCL"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jose-luna-b56239143/"